spring:
  datasource:
    url: jdbc:mysql://localhost:3333/todo_app?createDatabaseIfNotExist=true&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: YOUR_DB_USERNAME
    password: YOUR_DB_PASSWORD
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true

server:
  port: 8005

security:
  jwt:
    secret-key: 2ee657d85e2a97a2b8f456c6d61be4d469fff7b6be68c0d509a8cfe4c7947819
    expiration-time: 3600000
